#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/com.thebitguru.wolservice.jar
cp $IPKG_OFFLINE_ROOT/usr/lib/luna/java/com.thebitguru.wolservice.jar /usr/lib/luna/java/com.thebitguru.wolservice.jar
rm -f /usr/share/dbus-1/system-services/com.thebitguru.wolservice.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/com.thebitguru.wolservice.service /usr/share/dbus-1/system-services/com.thebitguru.wolservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.accelservice
cp $IPKG_OFFLINE_ROOT/etc/event.d/org.webosinternals.accelservice /etc/event.d/org.webosinternals.accelservice

exit 0
